stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: unifi-api-img:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34072
timeout: 60
notification: {}
