stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: Unify-api
      registry: 127.0.0.1:34072
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
