stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: unifi-api-server:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34072
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./Deployment.yaml
timeout: 60
notification: {}
